"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const now=new Date(), todayDate=CalendarEngine.formatDate({year:now.getFullYear(),month:now.getMonth()+1,day:now.getDate()});
let state={view:"month",year:now.getFullYear(),month:now.getMonth()+1,selected:todayDate,weekStart:1,events:[],prefs:{theme:"system",weekStart:1}};
const palette={teal:"#087f78",blue:"#4a71c9",violet:"#8056bb",rose:"#cf6076",amber:"#c08a17",slate:"#87949c"};
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function currentMonth(){return {year:state.year,month:state.month};}
async function getLocal(keys){return typeof chrome!=="undefined"&&chrome.storage?.local?chrome.storage.local.get(keys):{};}
async function setLocal(obj){if(typeof chrome!=="undefined"&&chrome.storage?.local)await chrome.storage.local.set(obj);}
function applyPopupRoute(route){if(route.startsWith("event:"))openEvent(null,route.slice(6));else if(["month","week","year","agenda","print","tools","resources","settings"].includes(route))showView(route);}
async function init(){await (globalThis.CalendarResourcesReady||Promise.resolve());const local=await getLocal(["sameCalendar.preferences","sameCalendar.popupRoute"]);state.prefs=local["sameCalendar.preferences"]||state.prefs;state.weekStart=state.prefs.weekStart??1;state.events=await CalendarStore.read();$("#todayLabel").textContent=CalendarEngine.formatLongDate(todayDate,navigator.language,{month:"short",day:"numeric"});$("#weekStart").value=state.weekStart;$("#settingsWeekStart").value=state.weekStart;$(".weekStartSelect").value=state.weekStart;$("#theme").value=state.prefs.theme||"system";const date=CalendarEngine.parseDate(todayDate);$("#printMonth").value=`${date.year}-${String(date.month).padStart(2,"0")}`;$("#printYear").value=date.year;$("#toolDate").value=todayDate;$("#diffFrom").value=todayDate;$("#diffTo").value=CalendarEngine.addDays(todayDate,30);$("#addDate").value=todayDate;applyTheme();renderAll();bind();const hash=location.hash.slice(1),route=local["sameCalendar.popupRoute"]||hash;if(local["sameCalendar.popupRoute"]&&typeof chrome!=="undefined"&&chrome.storage?.local)await chrome.storage.local.remove("sameCalendar.popupRoute");applyPopupRoute(route);if(typeof chrome!=="undefined"&&chrome.storage?.onChanged)chrome.storage.onChanged.addListener((changes,area)=>{if(area!=="local"||!changes["sameCalendar.popupRoute"]?.newValue)return;applyPopupRoute(changes["sameCalendar.popupRoute"].newValue);chrome.storage.local.remove("sameCalendar.popupRoute");});}
function applyTheme(){const theme=state.prefs.theme||"system",dark=theme==="dark"||(theme==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.body.dataset.theme=dark?"dark":"light";}
function showView(view){state.view=view;$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$(".panel").forEach(p=>p.classList.toggle("active",p.dataset.panel===view));const names={month:"Month",week:"Week",year:"Year",agenda:"Agenda",print:"Print planner",tools:"Date tools",resources:"Printable resources",settings:"Settings & backup"};$("#viewTitle").textContent=names[view]||"Month";if(view==="resources")renderResources();if(view==="print")renderPrint();}
function eventItems(date){return state.events.filter(e=>e.date===date).sort((a,b)=>a.time.localeCompare(b.time)||a.title.localeCompare(b.title));}
function renderMonth(){const {year,month}=currentMonth(),lang=navigator.language;$("#monthTitle").textContent=`${CalendarEngine.monthName(month,lang)} ${year}`;const labels=Array.from({length:7},(_,i)=>{const wd=(i+state.weekStart)%7;return new Intl.DateTimeFormat(lang,{weekday:"short",timeZone:"UTC"}).format(new Date(Date.UTC(2023,0,1+wd)));});$("#monthLabels").innerHTML=labels.map(x=>`<span>${escapeHTML(x)}</span>`).join("");const dates=CalendarEngine.monthGrid(year,month,state.weekStart);$("#monthView").innerHTML=dates.map((iso,i)=>{const d=CalendarEngine.parseDate(iso),dayEvents=eventItems(iso),week=i%7===0?CalendarEngine.isoWeek(iso).week:null;return `<button class="month-cell ${d.month!==month?"other":""} ${iso===todayDate?"today":""}" data-date="${iso}" aria-label="${escapeHTML(CalendarEngine.formatLongDate(iso,lang))}; ${dayEvents.length} events"><span class="date-number"><span>${d.day}</span><span class="iso-number">${week?`W${String(week).padStart(2,"0")}`:""}</span></span>${dayEvents.slice(0,3).map(e=>`<span class="month-event ${e.color}" title="${escapeHTML(e.title)}">${e.time?`${e.time} `:""}${escapeHTML(e.title)}</span>`).join("")}${dayEvents.length>3?`<span class="month-event">+${dayEvents.length-3} more</span>`:""}</button>`}).join("");}
function renderWeek(){const p=CalendarEngine.parseDate(state.selected),offset=(CalendarEngine.weekday(p)-state.weekStart+7)%7,start=CalendarEngine.addDays(state.selected,-offset),days=Array.from({length:7},(_,i)=>CalendarEngine.addDays(start,i));$("#weekTitle").textContent=`Week of ${CalendarEngine.formatLongDate(start,navigator.language,{month:"short",day:"numeric"})}`;$("#weekView").innerHTML=days.map(iso=>`<article class="week-day"><h3>${escapeHTML(CalendarEngine.formatLongDate(iso,navigator.language,{weekday:"long"}))}</h3><div class="date">${escapeHTML(CalendarEngine.formatLongDate(iso,navigator.language,{month:"short",day:"numeric",year:"numeric"}))} · W${CalendarEngine.isoWeek(iso).week}</div>${eventItems(iso).map(e=>`<button class="month-event ${e.color}" data-edit="${escapeHTML(e.id)}">${e.time?`${e.time} `:""}${escapeHTML(e.title)}</button>`).join("")}<button class="week-add" data-new-date="${iso}">＋ Add plan</button></article>`).join("");}
function renderYear(){const y=state.year;$("#yearTitle").textContent=String(y);$("#yearView").innerHTML=Array.from({length:12},(_,m)=>{const dates=CalendarEngine.monthGrid(y,m+1,state.weekStart).filter(iso=>CalendarEngine.parseDate(iso).month===m+1),title=CalendarEngine.monthName(m+1,navigator.language);return `<article class="mini-month" data-month="${m+1}"><h3>${escapeHTML(title)}</h3><div class="mini-days">${dates.map(iso=>{const d=CalendarEngine.parseDate(iso),has=eventItems(iso).length>0;return `<b class="${has?"has-event":""}" data-date="${iso}" title="${has?eventItems(iso).length+" event(s)":""}">${d.day}</b>`}).join("")}</div></article>`}).join("");}
function renderAgenda(){const query=($("#eventSearch")?.value||"").trim().toLocaleLowerCase(),category=$("#categoryFilter")?.value||"",upcoming=state.events.filter(e=>e.date>=todayDate&&(!category||e.category===category)&&(!query||[e.date,e.title,e.description,e.category].join(" ").toLocaleLowerCase().includes(query))).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));const categories=[...new Set(state.events.map(e=>e.category).filter(Boolean))].sort();if($("#categoryFilter")){const selected=$("#categoryFilter").value;$("#categoryFilter").innerHTML='<option value="">All categories</option>'+categories.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join("");$("#categoryFilter").value=categories.includes(selected)?selected:"";}$("#agendaCount").textContent=`${upcoming.length} upcoming`;$("#agendaView").innerHTML=upcoming.length?upcoming.map(e=>`<article class="agenda-item"><div class="agenda-date">${escapeHTML(CalendarEngine.formatLongDate(e.date,navigator.language,{month:"short",day:"numeric",year:"numeric"}))}<br>${e.allDay?"All day":e.time||""}</div><i class="agenda-line" style="background:${palette[e.color]||palette.teal}"></i><div><div class="agenda-title">${escapeHTML(e.title)}</div><div class="agenda-note">${escapeHTML(e.category)}${e.description?` · ${escapeHTML(e.description)}`:""}</div></div><div class="event-actions"><button class="mini-action" data-edit="${escapeHTML(e.id)}">Edit</button><button class="mini-action" data-delete="${escapeHTML(e.id)}">Delete</button></div></article>`).join(""):'<div class="empty-state">No matching upcoming events. Adjust the filters or add an event.</div>';}
function renderAll(){renderMonth();renderWeek();renderYear();renderAgenda();}
function bind(){
  $$('[data-view]').forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
  $("#prev").onclick=()=>shift(-1);$("#next").onclick=()=>shift(1);$("#today").onclick=$("#todayJump").onclick=()=>{const p=CalendarEngine.parseDate(todayDate);state.year=p.year;state.month=p.month;state.selected=todayDate;renderAll();};
  $("#prevYear").onclick=()=>{state.year--;renderAll();};$("#nextYear").onclick=()=>{state.year++;renderAll();};
  $("#monthView").addEventListener("click",e=>{const cell=e.target.closest("[data-date]");if(!cell)return;state.selected=cell.dataset.date;if(e.detail===2)openEvent(null,state.selected);else{const p=CalendarEngine.parseDate(state.selected);state.year=p.year;state.month=p.month;renderAll();}});
  $("#weekView").addEventListener("click",e=>{const edit=e.target.closest("[data-edit]"),add=e.target.closest("[data-new-date]");if(edit)openEvent(edit.dataset.edit);if(add)openEvent(null,add.dataset.newDate);});
  $("#yearView").addEventListener("click",e=>{const month=e.target.closest("[data-month]");if(month){state.month=Number(month.dataset.month);state.selected=`${state.year}-${String(state.month).padStart(2,"0")}-01`;showView("month");renderAll();}});
  $("#agendaView").addEventListener("click",e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit)openEvent(edit.dataset.edit);if(del)deleteEvent(del.dataset.delete);});
  $("#eventSearch").addEventListener("input",renderAgenda);$("#categoryFilter").addEventListener("change",renderAgenda);
  $("#newEvent").onclick=()=>openEvent(null,state.selected||todayDate);$("#closeDialog").onclick=$("#cancelDialog").onclick=()=>$("#eventDialog").close();
  $("#eventForm").addEventListener("submit",saveEvent);$("#deleteEvent").onclick=()=>deleteEvent($("#eventId").value);$("#allDay").onchange=()=>{$("#eventTime").disabled=$("#allDay").checked;};
  $("#weekStart").onchange=async e=>{state.weekStart=Number(e.target.value);$(".weekStartSelect").value=state.weekStart;$("#settingsWeekStart").value=state.weekStart;state.prefs.weekStart=state.weekStart;await savePrefs();renderAll();};$(".weekStartSelect").onchange=e=>{$("#weekStart").value=e.target.value;$("#weekStart").dispatchEvent(new Event("change"));};$("#settingsWeekStart").onchange=e=>{$("#weekStart").value=e.target.value;$("#weekStart").dispatchEvent(new Event("change"));};
  $("#theme").onchange=async e=>{state.prefs.theme=e.target.value;await savePrefs();applyTheme();};
  $("#monthPrint").onclick=()=>{showView("print");$("#printMode").value="month";$("#printMonth").value=`${state.year}-${String(state.month).padStart(2,"0")}`;renderPrint();window.print();};
  ["printMode","printMonth","printYear","paper","orientation","printWeekStart","printTheme","includeEvents","notesArea"].forEach(id=>$("#"+id).addEventListener("change",renderPrint));$("#previewPrint").onclick=renderPrint;$("#printNow").onclick=()=>{renderPrint();window.print();};
  $("#checkDate").onclick=calcFacts;$("#calcDiff").onclick=()=>{try{$("#diffResult").textContent=`${CalendarEngine.dateDifference($("#diffFrom").value,$("#diffTo").value)} days from first date to second.`;}catch(e){$("#diffResult").textContent=e.message;}};$("#calcAdd").onclick=()=>{try{$("#addResult").textContent=CalendarEngine.formatLongDate(CalendarEngine.addDays($("#addDate").value,Number($("#dayOffset").value)),navigator.language);}catch(e){$("#addResult").textContent=e.message;}};
  $("#exportJSON").onclick=()=>download("same-calendar-backup.json",CalendarExports.backup(state.events),"application/json");$("#exportCSV").onclick=()=>download("same-calendar-events.csv",CalendarExports.toCSV(state.events),"text/csv;charset=utf-8");$("#exportICS").onclick=()=>download("same-calendar-events.ics",CalendarExports.toICS(state.events),"text/calendar;charset=utf-8");$("#importJSON").onchange=importJSON;$("#clearData").onclick=async()=>{if(confirm("Clear all Same Calendar events stored in this browser? Export a backup first if you may need them later.")){await CalendarStore.clear();state.events=[];renderAll();$("#backupMessage").textContent="All local events have been cleared.";}};
}
function shift(step){if(state.view==="year"){state.year+=step;}else{const base=new Date(Date.UTC(state.year,state.month-1+step,1));state.year=base.getUTCFullYear();state.month=base.getUTCMonth()+1;state.selected=CalendarEngine.formatDate({year:state.year,month:state.month,day:1});}renderAll();}
function openEvent(id,date){const e=id?state.events.find(x=>x.id===id):null;$("#eventForm").reset();$("#eventId").value=e?.id||"";$("#dialogTitle").textContent=e?"Edit event":"Add event";$("#eventName").value=e?.title||"";$("#eventDate").value=e?.date||date||todayDate;$("#eventTime").value=e?.time||"";$("#eventCategory").value=e?.category||"Personal";$("#allDay").checked=e?.allDay||false;$("#eventTime").disabled=$("#allDay").checked;$("#eventDescription").value=e?.description||"";$("#eventColor").value=e?.color||"teal";$("#formError").textContent="";$("#deleteEvent").classList.toggle("hidden",!e);$("#eventDialog").showModal();$("#eventName").focus();}
async function saveEvent(e){e.preventDefault();try{const saved=await CalendarStore.save({id:$("#eventId").value||undefined,title:$("#eventName").value,date:$("#eventDate").value,time:$("#eventTime").value,allDay:$("#allDay").checked,category:$("#eventCategory").value,description:$("#eventDescription").value,color:$("#eventColor").value});state.events=await CalendarStore.read();state.selected=saved.date;const p=CalendarEngine.parseDate(saved.date);state.year=p.year;state.month=p.month;$("#eventDialog").close();renderAll();}catch(err){$("#formError").textContent=err.message;}}
async function deleteEvent(id){if(!confirm("Delete this event from your local calendar?"))return;await CalendarStore.remove(id);state.events=await CalendarStore.read();$("#eventDialog").close();renderAll();}
async function savePrefs(){await setLocal({"sameCalendar.preferences":state.prefs});}
function calcFacts(){try{const date=$("#toolDate").value,p=CalendarEngine.parseDate(date),iso=CalendarEngine.isoWeek(date);$("#dateFacts").innerHTML=`${escapeHTML(CalendarEngine.formatLongDate(date,navigator.language))}<br>ISO week ${iso.week}, ${iso.year}<br>Day ${CalendarEngine.dayOfYear(date)} of ${CalendarEngine.isLeapYear(p.year)?366:365}<br>${CalendarEngine.isLeapYear(p.year)?"Leap year":"Common year"}`;}catch(e){$("#dateFacts").textContent=e.message;}}
function renderResources(){const p=CalendarEngine.parseDate(state.selected),resource=CalendarResources.get(CalendarEngine.monthName(p.month,"en"),p.year);if(resource){$("#resourceTitle").textContent=`${resource.month} ${resource.year} printable calendar`;$("#resourceDescription").textContent=resource.description+" Selected month and year match the verified page.";$("#selectedResource").href=resource.url;$("#selectedResource").textContent=`Open ${resource.month} ${resource.year} printable ↗`;}else{$("#resourceTitle").textContent=`${CalendarEngine.monthName(p.month,navigator.language)} ${p.year} resource`;$("#resourceDescription").textContent="A matching month-specific page is not in the verified directory yet. You can open the general monthly collection instead.";$("#selectedResource").href=CalendarResources.collections[0].url;$("#selectedResource").textContent="Open monthly collection ↗";}
$("#resourceMonths").innerHTML=CalendarResources.resources.map(r=>`<button class="resource-month" data-resource="${r.month}|${r.year}">${r.month} ${r.year}<small>Verified printable page ↗</small></button>`).join("");}
$("#resourceMonths").addEventListener("click",e=>{const b=e.target.closest("[data-resource]");if(!b)return;const [month,year]=b.dataset.resource.split("|");const r=CalendarResources.get(month,year);if(!r)return;const i=CalendarResources.resources.indexOf(r),monthNumber=i<3?10+i:i-2;state.selected=`${year}-${String(monthNumber).padStart(2,"0")}-01`;$("#resourceTitle").textContent=`${month} ${year} printable calendar` ;$("#resourceDescription").textContent=r.description+" Selected month and year match the verified page.";$("#selectedResource").href=r.url;$("#selectedResource").textContent=`Open ${month} ${year} printable ↗`;});
function renderPrint(){const type=$("#printMode").value||"month",firstOfMonth=$("#printMonth").value||`${state.year}-${String(state.month).padStart(2,"0")}`,parts=firstOfMonth.split("-").map(Number),year=Number($("#printYear").value)||parts[0],month=parts[1]||1,weekStart=Number($("#printWeekStart").value||state.weekStart),withEvents=$("#includeEvents").checked,blank=type==="blank",evts=state.events.filter(e=>withEvents),notes=$("#notesArea").value||"medium";
let title="",html="";
if(type==="year"){title=`${year} Calendar`;html=`<div class="year-grid">${Array.from({length:12},(_,m)=>`<div><h3>${CalendarEngine.monthName(m+1,navigator.language)}</h3>${printTable(year,m+1,weekStart,evts,false)}</div>`).join("")}</div>`;}
else if(type==="week"){const start=CalendarEngine.addDays(state.selected,-((CalendarEngine.weekday(state.selected)-weekStart+7)%7));const days=Array.from({length:7},(_,i)=>CalendarEngine.addDays(start,i));title=`Week of ${start}`;html=`<div class="week-print">${days.map(d=>`<section><h3>${CalendarEngine.formatLongDate(d,navigator.language,{weekday:"long",month:"short",day:"numeric"})}</h3>${(withEvents?eventItems(d):[]).map(e=>`<p>${e.time||""} ${escapeHTML(e.title)}</p>`).join("")}<div class="print-notes"></div></section>`).join("")}</div>`;}
else if(type==="checklist"){title=`${CalendarEngine.monthName(month,navigator.language)} ${year} · Deadline checklist`;const monthEvents=withEvents?evts.filter(e=>{const p=CalendarEngine.parseDate(e.date);return p.year===year&&p.month===month;}):[];html=`<ul class="deadline-list">${monthEvents.map(e=>`<li><input type="checkbox"> <b>${escapeHTML(e.date.slice(-2))}</b> ${escapeHTML(e.title)} <small>${escapeHTML(e.category)}</small></li>`).join("")}${Array.from({length:10},()=>'<li><input type="checkbox"> ________________________________</li>').join("")}</ul>`;}
else{title=`${blank?"Blank ":type==="events"?"Event planning · ":""}${CalendarEngine.monthName(month,navigator.language)} ${year}`;html=printTable(year,month,weekStart,evts,!blank);}
$("#printPreview").innerHTML=`<article class="print-sheet ${$("#printTheme").value}" style="--print-accent:${$("#printTheme").value==="color"?"#087f78":"#333"}"><h2>${escapeHTML(title)}</h2>${html}<div class="print-notes notes-${notes}"><strong>Notes</strong></div><footer class="print-footer">Same Calendar · Beta Calendars · ${new Date().toLocaleDateString(navigator.language)}</footer></article>`;let pageRule=document.querySelector("#printPageStyle");if(!pageRule){pageRule=document.createElement("style");pageRule.id="printPageStyle";document.head.append(pageRule);}pageRule.textContent=`@page { size: ${$("#paper").value} ${$("#orientation").value}; margin: 12mm; }`;}
function printTable(year,month,weekStart,events,showEvents){const labels=Array.from({length:7},(_,i)=>{const wd=(i+weekStart)%7;return new Intl.DateTimeFormat(navigator.language,{weekday:"short",timeZone:"UTC"}).format(new Date(Date.UTC(2023,0,1+wd)));});const dates=CalendarEngine.monthGrid(year,month,weekStart);return `<table class="print-table"><thead><tr>${labels.map(l=>`<th>${escapeHTML(l)}</th>`).join("")}</tr></thead><tbody>${Array.from({length:6},(_,r)=>`<tr>${dates.slice(r*7,r*7+7).map(iso=>{const p=CalendarEngine.parseDate(iso),inMonth=p.month===month,dayEvents=showEvents?events.filter(e=>e.date===iso):[];return `<td>${inMonth?p.day:""}${dayEvents.map(e=>`<br><small>${e.time?e.time+" ":""}${escapeHTML(e.title)}</small>`).join("")}</td>`}).join("")}</tr>`).join("")}</tbody></table>`;}
function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importJSON(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw new RangeError("Backup file must be smaller than 5 MB.");const data=await file.text(),out=await CalendarStore.importBackup(data,$("#restoreMode").value);state.events=out;renderAll();$("#backupMessage").textContent=`Restored ${out.length} event(s) locally.`;}catch(err){$("#backupMessage").textContent=`Could not restore backup: ${err.message}`;}e.target.value="";}
init();
