"use strict";
const today = new Date(); let visible = {year:today.getFullYear(),month:today.getMonth()+1}, selected = CalendarEngine.formatDate({year:today.getFullYear(),month:today.getMonth()+1,day:today.getDate()}), weekStart = 1, items=[];
const $ = s => document.querySelector(s);
async function load(){if(typeof chrome!=="undefined"&&chrome.storage?.local){const p=await chrome.storage.local.get(["sameCalendar.preferences"]);weekStart=p["sameCalendar.preferences"]?.weekStart ?? 1;}items=await CalendarStore.read();render();}
function render(){const lang=navigator.language||"en";$("#monthTitle").textContent=`${CalendarEngine.monthName(visible.month,lang)} ${visible.year}`;$("#weekdayLabels").innerHTML=Array.from({length:7},(_,i)=>{const d=(i+weekStart)%7;return `<span>${new Intl.DateTimeFormat(lang,{weekday:"short",timeZone:"UTC"}).format(new Date(Date.UTC(2023,0,1+d))).slice(0,2)}</span>`}).join("");
$("#monthGrid").innerHTML=CalendarEngine.monthGrid(visible.year,visible.month,weekStart).map(iso=>{const p=CalendarEngine.parseDate(iso),inMonth=p.month===visible.month,has=items.some(e=>e.date===iso);return `<button class="day ${inMonth?"":"other"} ${iso===selected?"selected":""} ${iso===CalendarEngine.formatDate({year:today.getFullYear(),month:today.getMonth()+1,day:today.getDate()})?"today":""}" data-date="${iso}" aria-label="${CalendarEngine.formatLongDate(iso,lang)}">${p.day}${has?'<i class="dot"></i>':''}</button>`}).join("");$("#selectedTitle").textContent=CalendarEngine.formatLongDate(selected,lang,{month:"short",day:"numeric",year:"numeric"});const day=items.filter(e=>e.date===selected);$("#dayEvents").innerHTML=day.length?day.map(e=>`<div class="event-row"><i class="event-color"></i><div><strong>${escapeHTML(e.title)}</strong><div class="event-meta">${e.allDay?"All day":e.time||""}${e.category?` · ${escapeHTML(e.category)}`:""}</div></div></div>`).join(""):'<div class="empty">Nothing planned. Add an event to get started.</div>';$("#eventCount").textContent=`${items.length} ${items.length===1?"event":"events"} · stored on this device`;}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
$("#monthGrid").addEventListener("click",e=>{const b=e.target.closest("button[data-date]");if(b){selected=b.dataset.date;const p=CalendarEngine.parseDate(selected);visible={year:p.year,month:p.month};render();}});
$("#prevMonth").onclick=()=>{visible.month--;if(visible.month<1){visible.month=12;visible.year--;}render();};$("#nextMonth").onclick=()=>{visible.month++;if(visible.month>12){visible.month=1;visible.year++;}render();};$("#todayBtn").onclick=()=>{visible={year:today.getFullYear(),month:today.getMonth()+1};selected=CalendarEngine.formatDate({year:today.getFullYear(),month:today.getMonth()+1,day:today.getDate()});render();};
function openPlanner(view){const url=typeof chrome!=="undefined"&&chrome.runtime?.getURL?chrome.runtime.getURL(`planner.html${view?`#${view}`:""}`):`planner.html${view?`#${view}`:""}`;if(typeof chrome!=="undefined"&&chrome.tabs)chrome.tabs.create({url});else location.href=url;}
$("#openPlanner").onclick=()=>openPlanner("month");$("#openSettings").onclick=()=>openPlanner("settings");$("#addEvent").onclick=()=>openPlanner(`event:${selected}`);load();
