(function(root){"use strict";
  function safeSpreadsheet(value){let s=String(value ?? ""); if(/^[\s]*[=+@\-]/.test(s)) s="'"+s; return `"${s.replaceAll('"','""')}"`;}
  function toCSV(events){const lines=[["Date","Time","All day","Title","Description","Category","Color"].map(safeSpreadsheet).join(",")]; for(const e of events) lines.push([e.date,e.time,e.allDay?"Yes":"No",e.title,e.description,e.category,e.color].map(safeSpreadsheet).join(",")); return "\uFEFF"+lines.join("\r\n");}
  function icsEscape(value){return String(value ?? "").replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");}
  function foldLine(line){const out=[];let current="",bytes=0; for(const char of line){const size=new TextEncoder().encode(char).length;if(bytes+size>73){out.push(current);current=" ";bytes=1;}current+=char;bytes+=size;}out.push(current);return out.join("\r\n");}
  function toICS(events){const stamp=new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Beta Calendars//Same Calendar 1.0//EN","CALSCALE:GREGORIAN","METHOD:PUBLISH"];
    for(const e of events){lines.push("BEGIN:VEVENT",`UID:${icsEscape(e.id)}@same-calendar.betacalendars.com`,`DTSTAMP:${stamp}`); if(e.allDay){const next=root.CalendarEngine.addDays(e.date,1).replaceAll("-","");lines.push(`DTSTART;VALUE=DATE:${e.date.replaceAll("-","")}`,`DTEND;VALUE=DATE:${next}`);}else{const p=root.CalendarEngine.parseDate(e.date),hm=(e.time||"09:00").split(":").map(Number),start=new Date(0);start.setUTCHours(hm[0],hm[1],0,0);start.setUTCFullYear(p.year,p.month-1,p.day);const end=new Date(start.getTime()+3600000),stampDate=d=>`${String(d.getUTCFullYear()).padStart(4,"0")}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}T${String(d.getUTCHours()).padStart(2,"0")}${String(d.getUTCMinutes()).padStart(2,"0")}00`;lines.push(`DTSTART:${stampDate(start)}`,`DTEND:${stampDate(end)}`);}lines.push(`SUMMARY:${icsEscape(e.title)}`);if(e.description)lines.push(`DESCRIPTION:${icsEscape(e.description)}`);if(e.category)lines.push(`CATEGORIES:${icsEscape(e.category)}`);lines.push("END:VEVENT");}
    lines.push("END:VCALENDAR"); return lines.map(foldLine).join("\r\n")+"\r\n";}
  function backup(events){return JSON.stringify({format:"same-calendar-backup",version:1,createdAt:new Date().toISOString(),events},null,2);}
  root.CalendarExports={toCSV,toICS,backup,icsEscape,foldLine}; if(typeof module!=="undefined"&&module.exports)module.exports=root.CalendarExports;
})(typeof globalThis!=="undefined"?globalThis:this);
